import React from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Dumbbell, Brain, TrendingUp, Users, Zap, Target } from 'lucide-react';

const Index = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-fitness-50 to-fitness-100 dark:from-gray-900 dark:to-gray-800">
      {/* Hero Section */}
      <div className="container mx-auto px-4 py-16">
        <div className="text-center space-y-6 mb-16">
          <h1 className="text-5xl font-bold bg-gradient-to-r from-fitness-600 to-fitness-700 bg-clip-text text-transparent">
            FitTrack AI
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Transform your fitness journey with AI-powered workout planning, intelligent tracking, and personalized coaching
          </p>
          <div className="flex gap-4 justify-center">
            <Button asChild size="lg" variant="fitness">
              <Link to="/register">Get Started</Link>
            </Button>
            <Button variant="fitness-outline" size="lg" asChild>
              <Link to="/login">Sign In</Link>
            </Button>
          </div>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-16">
          <Card className="fitness-card border-2 border-fitness-200/50 hover:border-fitness-500/50 transition-all duration-200 hover:shadow-xl">
            <CardHeader>
              <Brain className="h-12 w-12 text-fitness-600 mb-2" />
              <CardTitle>AI-Powered Workouts</CardTitle>
              <CardDescription>
                Get personalized workout plans generated by advanced AI based on your goals and fitness level
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="fitness-card border-2 fitness-border-light/50 hover:fitness-border/50 transition-all duration-200 hover:shadow-xl">
            <CardHeader>
              <TrendingUp className="h-12 w-12 fitness-text-primary mb-2" />
              <CardTitle>Smart Progress Tracking</CardTitle>
              <CardDescription>
                Monitor your fitness journey with intelligent analytics and detailed progress insights
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="fitness-card border-2 fitness-border-light/50 hover:fitness-border/50 transition-all duration-200 hover:shadow-xl">
            <CardHeader>
              <Dumbbell className="h-12 w-12 fitness-text-primary mb-2" />
              <CardTitle>Comprehensive Exercise Library</CardTitle>
              <CardDescription>
                Access a vast database of exercises with proper form instructions and video demonstrations
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="fitness-card border-2 fitness-border-light/50 hover:fitness-border/50 transition-all duration-200 hover:shadow-xl">
            <CardHeader>
              <Target className="h-12 w-12 fitness-text-primary mb-2" />
              <CardTitle>Goal-Oriented Planning</CardTitle>
              <CardDescription>
                Set and achieve specific fitness goals with structured plans tailored to your objectives
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="fitness-card border-2 fitness-border-light/50 hover:fitness-border/50 transition-all duration-200 hover:shadow-xl">
            <CardHeader>
              <Zap className="h-12 w-12 fitness-text-primary mb-2" />
              <CardTitle>Real-time Coaching</CardTitle>
              <CardDescription>
                Get instant feedback and coaching tips powered by AI to optimize your workout performance
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="fitness-card border-2 fitness-border-light/50 hover:fitness-border/50 transition-all duration-200 hover:shadow-xl">
            <CardHeader>
              <Users className="h-12 w-12 fitness-text-primary mb-2" />
              <CardTitle>Community Support</CardTitle>
              <CardDescription>
                Connect with fellow fitness enthusiasts and share your journey with a supportive community
              </CardDescription>
            </CardHeader>
          </Card>
        </div>

        {/* CTA Section */}
        <Card className="fitness-card border-2 fitness-border-light bg-gradient-to-r from-fitness-50/80 to-fitness-100/80 dark:from-gray-800/80 dark:to-gray-700/80">
          <CardContent className="p-8 text-center">
            <CardTitle className="text-2xl mb-4">Ready to Transform Your Fitness?</CardTitle>
            <CardDescription className="text-lg mb-6">
              Join thousands of users who have already achieved their fitness goals with FitTrack AI
            </CardDescription>
            <Button size="lg" asChild variant="fitness">
              <Link to="/register">Start Your Journey Today</Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Index;